In [1]:
import pandas as pd

train_df = pd.read_csv(
    r"E:\ADS2002_Melanoma\data\splits\train.csv"
)

val_df = pd.read_csv(
    r"E:\ADS2002_Melanoma\data\splits\validation.csv"
)

test_df = pd.read_csv(
    r"E:\ADS2002_Melanoma\data\splits\test.csv"
)

print("Training:", len(train_df))
print("Validation:", len(val_df))
print("Test:", len(test_df))

Training: 23098
Validation: 4657
Test: 4946

In [2]:
features = [
    "age_approx",
    "sex",
    "anatom_site_general_challenge"
]

In [4]:
# X = information used to make prediction
# y = answer we're trying to predict

X_train = train_df[features].copy()
X_val = val_df[features].copy()
X_test = test_df[features].copy()

y_train = train_df["target"]
y_val = val_df["target"]
y_test = test_df["target"]

In [ ]:
# handle age missing values

train_age_median = X_train["age_approx"].median()

print("Training median age:", train_age_median)

Training median age: 50.0

In [6]:
X_train['age_approx'] = X_train['age_approx'].fillna(
    train_age_median
)

X_val['age_approx'] = X_val['age_approx'].fillna(
    train_age_median
)

X_test['age_approx'] = X_test['age_approx'].fillna(
    train_age_median
)

In [8]:
# handle sex and site missing values
X_train["sex"] = X_train["sex"].fillna("missing")
X_val["sex"] = X_val["sex"].fillna("missing")
X_test["sex"] = X_test["sex"].fillna("missing")

X_train["anatom_site_general_challenge"] = (
    X_train["anatom_site_general_challenge"].fillna("missing")
)

X_val["anatom_site_general_challenge"] = (
    X_val["anatom_site_general_challenge"].fillna("missing")
)

X_test["anatom_site_general_challenge"] = (
    X_test["anatom_site_general_challenge"].fillna("missing")
)

print(X_train.isnull().sum())

age_approx                       0
sex                              0
anatom_site_general_challenge    0
dtype: int64

In [11]:
'''
Convert words into numbers:
male
female
torso
head/neck
'''

from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(
    handle_unknown="ignore",
    sparse_output=False
)

In [12]:
categorical_features = [
    "sex",
    "anatom_site_general_challenge"
]

encoder.fit(X_train[categorical_features])

OneHotEncoder(handle_unknown='ignore', sparse_output=False)

In [13]:
train_encoded = encoder.transform(
    X_train[categorical_features]
)

val_encoded = encoder.transform(
    X_val[categorical_features]
)

test_encoded = encoder.transform(
    X_test[categorical_features]
)

In [14]:
encoded_names = encoder.get_feature_names_out(
    categorical_features
)

print(encoded_names)

['sex_female' 'sex_male' 'sex_missing'
 'anatom_site_general_challenge_head/neck'
 'anatom_site_general_challenge_lower extremity'
 'anatom_site_general_challenge_missing'
 'anatom_site_general_challenge_oral/genital'
 'anatom_site_general_challenge_palms/soles'
 'anatom_site_general_challenge_torso'
 'anatom_site_general_challenge_upper extremity']

In [15]:
import numpy as np

X_train_final = np.column_stack([
    X_train["age_approx"].values,
    train_encoded
])

X_val_final = np.column_stack([
    X_val["age_approx"].values,
    val_encoded
])

X_test_final = np.column_stack([
    X_test["age_approx"].values,
    test_encoded
])

In [16]:
print("Training X shape:", X_train_final.shape)
print("Validation X shape:", X_val_final.shape)
print("Test X shape:", X_test_final.shape)

Training X shape: (23098, 11)
Validation X shape: (4657, 11)
Test X shape: (4946, 11)

In [17]:
from sklearn.linear_model import LogisticRegression

In [18]:
model = LogisticRegression(
    class_weight="balanced",
    max_iter=1000
)

model.fit(X_train_final, y_train)

LogisticRegression(class_weight='balanced', max_iter=1000)

In [20]:
# Make predictions on VALIDATION

val_probabilities = model.predict_proba(
    X_val_final
)[:, 1]

print(val_probabilities)

[0.64827384 0.52051928 0.5714215  ... 0.35558578 0.47643686 0.47643686]

In [21]:
# Calculate ROC-AUC and PR-AUC
from sklearn.metrics import roc_auc_score
from sklearn.metrics import average_precision_score

In [23]:
roc_auc = roc_auc_score(
    y_val,
    val_probabilities
)

pr_auc = average_precision_score(
    y_val,
    val_probabilities
)

print("Validation ROC-AUC:", roc_auc)
print("Validation PR-AUC:", pr_auc)

'''
Patient metadata alone contains some melanoma-related signal, but we still need to see whether image information performs substantially better.
'''

Validation ROC-AUC: 0.696079468309097
Validation PR-AUC: 0.05751401705262359

'\nPatient metadata alone contains some melanoma-related signal, but we still need to see whether image information performs substantially better.\n'

In [24]:
# Convert probabilities into predictions
val_predictions = []

for probability in val_probabilities:

    if probability >= 0.5:
        val_predictions.append(1)

    else:
        val_predictions.append(0)

In [27]:
# Confusion matrix
from sklearn.metrics import confusion_matrix
'''
TN = True Negative
     benign → correctly predicted benign

FP = False Positive
     benign → incorrectly predicted melanoma

FN = False Negative
     melanoma → incorrectly predicted benign

TP = True Positive
     melanoma → correctly predicted melanoma
'''

'\nTN = True Negative\n     benign → correctly predicted benign\n\nFP = False Positive\n     benign → incorrectly predicted melanoma\n\nFN = False Negative\n     melanoma → incorrectly predicted benign\n\nTP = True Positive\n     melanoma → correctly predicted melanoma\n'

In [26]:
cm = confusion_matrix(
    y_val,
    val_predictions
)

print(cm)

[[3190 1378]
 [  33   56]]

In [28]:
tn = cm[0][0]
fp = cm[0][1]
fn = cm[1][0]
tp = cm[1][1]

print("True Negative:", tn)
print("False Positive:", fp)
print("False Negative:", fn)
print("True Positive:", tp)

True Negative: 3190
False Positive: 1378
False Negative: 33
True Positive: 56

In [32]:
sensitivity = tp / (tp + fn)

print("Sensitivity:", sensitivity)

specificity = tn / (tn + fp)

print("Specificity:", specificity)

precision = tp / (tp + fp)

print("Precision:", precision)

Sensitivity: 0.6292134831460674
Specificity: 0.6983362521891419
Precision: 0.03905160390516039

In [34]:
print("Validation results")
print("------------------")

print("ROC-AUC:", roc_auc)
print("PR-AUC:", pr_auc)
print("Sensitivity:", round(sensitivity * 100, 2), "%")
print("Specificity:", round(specificity * 100, 2), "%")
print("Precision:", round(precision * 100, 2), "%")

Validation results
------------------
ROC-AUC: 0.696079468309097
PR-AUC: 0.05751401705262359
Sensitivity: 62.92 %
Specificity: 69.83 %
Precision: 3.91 %

# Try several thresholds

In [35]:
thresholds = [
    0.1,
    0.2,
    0.3,
    0.4,
    0.5,
    0.6,
    0.7,
    0.8,
    0.9
]

for threshold in thresholds:

    predictions = []

    for probability in val_probabilities:

        if probability >= threshold:
            predictions.append(1)

        else:
            predictions.append(0)

    cm = confusion_matrix(
        y_val,
        predictions
    )

    tn = cm[0][0]
    fp = cm[0][1]
    fn = cm[1][0]
    tp = cm[1][1]

    sensitivity = tp / (tp + fn)
    specificity = tn / (tn + fp)

    print("Threshold:", threshold)
    print("Sensitivity:", round(sensitivity * 100, 2), "%")
    print("Specificity:", round(specificity * 100, 2), "%")
    print()

Threshold: 0.1
Sensitivity: 100.0 %
Specificity: 0.0 %

Threshold: 0.2
Sensitivity: 98.88 %
Specificity: 0.92 %

Threshold: 0.3
Sensitivity: 95.51 %
Specificity: 8.91 %

Threshold: 0.4
Sensitivity: 77.53 %
Specificity: 42.54 %

Threshold: 0.5
Sensitivity: 62.92 %
Specificity: 69.83 %

Threshold: 0.6
Sensitivity: 42.7 %
Specificity: 85.18 %

Threshold: 0.7
Sensitivity: 15.73 %
Specificity: 96.39 %

Threshold: 0.8
Sensitivity: 4.49 %
Specificity: 99.39 %

Threshold: 0.9
Sensitivity: 0.0 %
Specificity: 100.0 %

In [36]:
thresholds = np.arange(
    0.1,
    0.91,
    0.05
)

print(thresholds)

[0.1  0.15 0.2  0.25 0.3  0.35 0.4  0.45 0.5  0.55 0.6  0.65 0.7  0.75
 0.8  0.85 0.9 ]

In [38]:
results = []

for threshold in thresholds:

    predictions = []

    for probability in val_probabilities:

        if probability >= threshold:
            predictions.append(1)

        else:
            predictions.append(0)

    cm = confusion_matrix(
        y_val,
        predictions
    )

    tn = cm[0][0]
    fp = cm[0][1]
    fn = cm[1][0]
    tp = cm[1][1]

    sensitivity = tp / (tp + fn)
    specificity = tn / (tn + fp)

    results.append([
        threshold,
        sensitivity,
        specificity
    ])

threshold_results = pd.DataFrame(
    results,
    columns=[
        "threshold",
        "sensitivity",
        "specificity"
    ]
)

display(threshold_results)

    threshold  sensitivity  specificity
0        0.10     1.000000     0.000000
1        0.15     1.000000     0.000000
2        0.20     0.988764     0.009194
3        0.25     0.977528     0.052977
4        0.30     0.955056     0.089098
5        0.35     0.943820     0.189799
6        0.40     0.775281     0.425350
7        0.45     0.696629     0.572023
8        0.50     0.629213     0.698336
9        0.55     0.505618     0.779772
10       0.60     0.426966     0.851795
11       0.65     0.258427     0.943739
12       0.70     0.157303     0.963879
13       0.75     0.067416     0.984895
14       0.80     0.044944     0.993870
15       0.85     0.022472     0.998249
16       0.90     0.000000     1.000000

In [41]:
'''
The classification threshold was selected using the validation set by maximising Youden's J statistic, balancing sensitivity and specificity.
'''
threshold_results["youden_j"] = (
    threshold_results["sensitivity"]
    +
    threshold_results["specificity"]
    -
    1
)

display(threshold_results)

best_row = threshold_results[
    threshold_results["youden_j"]
    ==
    threshold_results["youden_j"].max()
]

display(best_row)

    threshold  sensitivity  specificity  youden_j
0        0.10     1.000000     0.000000  0.000000
1        0.15     1.000000     0.000000  0.000000
2        0.20     0.988764     0.009194 -0.002042
3        0.25     0.977528     0.052977  0.030505
4        0.30     0.955056     0.089098  0.044154
5        0.35     0.943820     0.189799  0.133619
6        0.40     0.775281     0.425350  0.200631
7        0.45     0.696629     0.572023  0.268652
8        0.50     0.629213     0.698336  0.327550
9        0.55     0.505618     0.779772  0.285390
10       0.60     0.426966     0.851795  0.278761
11       0.65     0.258427     0.943739  0.202166
12       0.70     0.157303     0.963879  0.121183
13       0.75     0.067416     0.984895  0.052311
14       0.80     0.044944     0.993870  0.038814
15       0.85     0.022472     0.998249  0.020721
16       0.90     0.000000     1.000000  0.000000

   threshold  sensitivity  specificity  youden_j
8        0.5     0.629213     0.698336   0.32755

In [42]:
thresholds = [
    0.45,
    0.46,
    0.47,
    0.48,
    0.49,
    0.50,
    0.51,
    0.52,
    0.53,
    0.54,
    0.55
]

results = []

for threshold in thresholds:

    predictions = []

    for probability in val_probabilities:

        if probability >= threshold:
            predictions.append(1)
        else:
            predictions.append(0)

    cm = confusion_matrix(y_val, predictions)

    tn = cm[0][0]
    fp = cm[0][1]
    fn = cm[1][0]
    tp = cm[1][1]

    sensitivity = tp / (tp + fn)
    specificity = tn / (tn + fp)

    youden_j = sensitivity + specificity - 1

    results.append([
        threshold,
        sensitivity,
        specificity,
        youden_j
    ])

In [43]:
fine_threshold_results = pd.DataFrame(
    results,
    columns=[
        "threshold",
        "sensitivity",
        "specificity",
        "youden_j"
    ]
)

display(fine_threshold_results)

best_row = fine_threshold_results[
    fine_threshold_results["youden_j"]
    ==
    fine_threshold_results["youden_j"].max()
]

display(best_row)

    threshold  sensitivity  specificity  youden_j
0        0.45     0.696629     0.572023  0.268652
1        0.46     0.696629     0.572023  0.268652
2        0.47     0.696629     0.580123  0.276752
3        0.48     0.651685     0.666156  0.317841
4        0.49     0.629213     0.698336  0.327550
5        0.50     0.629213     0.698336  0.327550
6        0.51     0.606742     0.704685  0.311426
7        0.52     0.539326     0.731830  0.271156
8        0.53     0.505618     0.779772  0.285390
9        0.54     0.505618     0.779772  0.285390
10       0.55     0.505618     0.779772  0.285390

   threshold  sensitivity  specificity  youden_j
4       0.49     0.629213     0.698336   0.32755
5       0.50     0.629213     0.698336   0.32755

In [45]:
best_threshold = 0.49

# Final evaluation on the test set

In [46]:
test_probabilities = model.predict_proba(
    X_test_final
)[:, 1]

test_roc_auc = roc_auc_score(
    y_test,
    test_probabilities
)

test_pr_auc = average_precision_score(
    y_test,
    test_probabilities
)

test_predictions = []

for probability in test_probabilities:

    if probability >= best_threshold:
        test_predictions.append(1)
    else:
        test_predictions.append(0)

In [47]:
test_cm = confusion_matrix(
    y_test,
    test_predictions
)

print(test_cm)

tn = test_cm[0][0]
fp = test_cm[0][1]
fn = test_cm[1][0]
tp = test_cm[1][1]

print("True Negative:", tn)
print("False Positive:", fp)
print("False Negative:", fn)
print("True Positive:", tp)

[[3069 1781]
 [  37   59]]
True Negative: 3069
False Positive: 1781
False Negative: 37
True Positive: 59

In [48]:
test_sensitivity = tp / (tp + fn)
test_specificity = tn / (tn + fp)
test_precision = tp / (tp + fp)

print("TEST RESULTS")
print("------------------")

print("ROC-AUC:", round(test_roc_auc, 4))
print("PR-AUC:", round(test_pr_auc, 4))

print(
    "Sensitivity:",
    round(test_sensitivity * 100, 2),
    "%"
)

print(
    "Specificity:",
    round(test_specificity * 100, 2),
    "%"
)

print(
    "Precision:",
    round(test_precision * 100, 2),
    "%"
)

print("Threshold:", best_threshold)

TEST RESULTS
------------------
ROC-AUC: 0.694
PR-AUC: 0.0667
Sensitivity: 61.46 %
Specificity: 63.28 %
Precision: 3.21 %
Threshold: 0.49

In [49]:
import os
import joblib

model_folder = r"E:\ADS2002_Melanoma\models\metadata"

os.makedirs(model_folder, exist_ok=True)

In [50]:
joblib.dump(
    model,
    model_folder + r"\logistic_regression.pkl"
)

['E:\\ADS2002_Melanoma\\models\\metadata\\logistic_regression.pkl']

In [51]:
joblib.dump(
    encoder,
    model_folder + r"\one_hot_encoder.pkl"
)

['E:\\ADS2002_Melanoma\\models\\metadata\\one_hot_encoder.pkl']

In [52]:
settings = {
    "age_median": train_age_median,
    "threshold": best_threshold
}

joblib.dump(
    settings,
    model_folder + r"\settings.pkl"
)

print("Metadata model saved.")

Metadata model saved.